[project]
authors = ["hinxcode <hinx@uw.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "digital-collections-explorer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
